bind = "0.0.0.0:5000"
workers = 4
# timeout = 30
accesslog = "-"
errorlog = "-"

# Gunicorn issues 
# WORKER TIMEOUT - TIMEOUT WAS DEFAULTED TO 30 SECONDS
# WHEN ONE WORKER WAS KILLED, THE DB CONNECTION WAS NOT PROPERLY CLOSED? AND THE REQUEST COULD NOT BE COMPLETED
# INCREASING THE TIMEOUT TO 120 SECONDS HELPED